import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { ReactQueryProvider } from "@/modules/react-query/ReactQueryProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { AuthProvider } from "@/modules/auth/AuthProvider/AuthProvider";
import { G } from "@mobily/ts-belt";
import { ssrGetUser } from "@/modules/auth/ssrGetUser";
import { Toaster } from "sonner";
import { ProgressProvider } from "@/modules/ProgressProvider/ProgressProvider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Manshure Fanavari",
	description: "Generated by create next app",
};

export const RootLayout = async ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	const user = await ssrGetUser();

	return (
		<ReactQueryProvider>
			<html lang="en">
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<ProgressProvider>
						<AuthProvider
							initialData={G.isNotNullable(user) ? user : undefined}
						>
							{children}
							<ReactQueryDevtools
								buttonPosition="bottom-right"
								initialIsOpen={false}
							/>
						</AuthProvider>
					</ProgressProvider>
					<Toaster />
				</body>
			</html>
		</ReactQueryProvider>
	);
};
